# Docker
# Build a Docker image
# https://docs.microsoft.com/azure/devops/pipelines/languages/docker

trigger:
- master

resources:
- repo: self

variables:
  tag: '$(Build.BuildId)'

stages:
- stage: Build
  displayName: Build image
  jobs:
  - job: Build
    displayName: Build
    pool: Tower DOCKER
    steps:

    - task: DockerInstaller@0
      displayName: Install Docker 20.X
      inputs:
        dockerVersion: '20.10.7'
    
    - task: Docker@2
      displayName: Login to docker registry
      inputs:
        containerRegistry: '3dextended registry azure'
        command: 'login'

    - task: CmdLine@2
      displayName: Build image for platform linux/arm/v7
      enabled: true
      inputs:
        script: |
          docker --version
          sudo docker run --privileged --rm tonistiigi/binfmt --install all
          sudo docker buildx use ci-builder
          sudo docker buildx inspect --bootstrap
          sudo docker buildx build -t 3dextended/yetanotherbot:$(tag)raspberrypi -t 3dextended.azurecr.io/yetanotherbot:$(tag)raspberrypi . --platform linux/arm/v7
          sudo docker buildx build -t 3dextended/yetanotherbot:$(tag) -t 3dextended.azurecr.io/yetanotherbot:$(tag) . --platform linux/amd64

    - task: Docker@2
      displayName: push custom platform version of image
      inputs:
        containerRegistry: '3dextended registry azure'
        repository: 'yetanotherbot'
        command: 'push'
        tags: '$(tag)raspberrypi'

    - task: Docker@2
      displayName: push custom platform version of image
      inputs:
        containerRegistry: '3dextended registry azure'
        repository: 'yetanotherbot'
        command: 'push'
        tags: '$(tag)'
    
    - task: Docker@2
      inputs:
        containerRegistry: 'Dockerhub 3DExtended'
        command: 'login'
    
    - task: Docker@2
      inputs:
        containerRegistry: 'Dockerhub 3DExtended'
        command: 'push'
        repository: '3dextended/yetanotherbot'
        tags: |
          3dextended/yetanotherbot:$(tag)raspberrypi
          3dextended/yetanotherbot:$(tag)