# Docker
# Build a Docker image
# https://docs.microsoft.com/azure/devops/pipelines/languages/docker

trigger:
- master

resources:
- repo: self

variables:
  tag: '$(Build.BuildId)'

stages:
- stage: Build
  displayName: Build image
  jobs:
  - job: BuildAMDVersion
    displayName: Build
    pool:
      vmImage: ubuntu-latest
    steps:

    - task: Docker@2
      displayName: Build and push image for linux/amd64
      inputs:
       containerRegistry: '3dextended registry azure'
       repository: 'yetanotherbot'
       command: 'buildAndPush'
       Dockerfile: '**/Dockerfile'
       tags: '$(tag)'

  - job: BuildARMVersion
    displayName: Build
    pool: Tower DOCKER
    steps:

    - task: DockerInstaller@0
      displayName: Install Docker 20.X
      inputs:
        dockerVersion: '20.10.7'
    
    - task: Docker@2
      displayName: Login to docker registry
      inputs:
        containerRegistry: '3dextended registry azure'
        command: 'login'

    - task: CmdLine@2
      displayName: Build image for platform linux/arm/v7 TEST
      inputs:
        script: |
          docker --version
          docker build -t 3dextended.azurecr.io/yetanotherbot:$(tag)raspberrypi .
    
    - task: CmdLine@2
      displayName: Build image for platform linux/arm/v7
      inputs:
        script: |
          docker --version
          docker run --privileged --rm tonistiigi/binfmt --install all
          docker buildx use ci-builder
          docker buildx build -t 3dextended.azurecr.io/yetanotherbot:$(tag)raspberrypi . --platform linux/arm/v7 --build-arg rpi=42

    - task: Docker@2
      displayName: push custom platform version of image
      inputs:
        containerRegistry: '3dextended registry azure'
        repository: 'yetanotherbot'
        command: 'push'
        tags: '$(tag)raspberrypi'