# Docker
# Build a Docker image
# https://docs.microsoft.com/azure/devops/pipelines/languages/docker

trigger:
- master

resources:
- repo: self

variables:
  tag: '$(Build.BuildId)'

stages:
- stage: Build
  displayName: Build image
  jobs:
  - job: Build
    displayName: Build
    pool:
      vmImage: ubuntu-latest
    steps:

    - task: DockerInstaller@0
      displayName: Install Docker 20.X
      inputs:
        dockerVersion: '20.10.7'
    
    - task: CmdLine@2
      displayName: Build image for platform linux/arm/v7
      inputs:
        script: |
          docker --version
          docker buildx build -t $(tag)-raspberryPi . --platform linux/arm/v7

    - task: Docker@2
      displayName: Build and push image for linux/amd64
      inputs:
       containerRegistry: '3dextended registry azure'
       repository: 'yetanotherbot'
       command: 'buildAndPush'
       Dockerfile: '**/Dockerfile'
       tags: '$(tag)'
       
    - task: Docker@2
      displayName: Login to docker registry
      inputs:
        containerRegistry: '3dextended registry azure'
        command: 'login'

#    - task: CmdLine@2
#      inputs:
#        script: |
#          docker image push registry-host:5000/myadmin/rhel-httpd:$(tag)-raspberryPi
#
    - task: Docker@2
      displayName: push custom platform version of image
      inputs:
        containerRegistry: '3dextended registry azure'
        repository: 'yetanotherbot'
        command: 'push'
        tags: '$(tag)-raspberryPi'