# Docker
# Build a Docker image
# https://docs.microsoft.com/azure/devops/pipelines/languages/docker

trigger:
- master

resources:
- repo: self

variables:
  tag: '$(Build.BuildId)'

stages:
- stage: Build
  displayName: Build image
  jobs:
  - job: BuildAMDVersion
    dependsOn: BuildARMVersion
    displayName: Build
    pool:
      vmImage: ubuntu-latest
    steps:

    - task: Docker@2
      displayName: Build and push image for linux/amd64
      inputs:
       containerRegistry: '3dextended registry azure'
       repository: 'yetanotherbot'
       command: 'buildAndPush'
       Dockerfile: '**/Dockerfile'
       tags: '$(tag)'

  - job: BuildARMVersion
    displayName: Build
    pool:
      vmImage: ubuntu-latest
    steps:

    - task: DockerInstaller@0
      displayName: Install Docker 20.X
      inputs:
        dockerVersion: '20.10.7'
    
    - task: CmdLine@2
      displayName: Build image for platform linux/arm/v7
      inputs:
        script: |
          docker --version
          docker run --privileged --rm tonistiigi/binfmt --install all
          docker buildx create --name mybuilder --use
          docker buildx build -t $(tag)-raspberrypi . --platform linux/arm/v7 --build-arg BASE_IMAGE=aspnet:5.0.9-buster-slim-arm32v7 --build-arg BUILD_IMAGE=sdk:5.0.400-buster-slim-arm32v7
       
    - task: Docker@2
      displayName: Login to docker registry
      inputs:
        containerRegistry: '3dextended registry azure'
        command: 'login'

#    - task: CmdLine@2
#      inputs:
#        script: |
#          docker image push registry-host:5000/myadmin/rhel-httpd:$(tag)-raspberrypi
#
    - task: Docker@2
      displayName: push custom platform version of image
      inputs:
        containerRegistry: '3dextended registry azure'
        repository: 'yetanotherbot'
        command: 'push'
        tags: '$(tag)-raspberrypi'